spring:
  application:
    name: gridgain-gs

logging:
  file: /var/tmp/logs/gridgain-gs/gridgain-gs
  level:
    root: INFO
    poc.ignite: debug

ignite:
  ips:
    - 172.17.5.36:42500..42700
    - 172.17.5.31:42500..42700
    
  dataRegion: #MB
    initial: 512
    max: 1024
  
  other:
    nodeName: worker-node
    records: 25000
    clientMode: true
  
  cache:
    backups: 1
  
  threads:
    enabled: 1
    system: 4
    public: 4
    queries: 4
    service: 4
    striped: 4
    dataStreamer: 4
    igfs: 4
    management: 4
    peerClass: 2
    rebalance: 1
    utilityCache: 4
