spring:
  application:
    name: ignite-transactions

logging:
  file: /var/tmp/logs/ignite-transactions/ignite-transactions
  level:
    root: INFO
    poc.ignite: debug

ignite:
  ips:
    - 172.17.5.36:42500..42700
    #- 172.17.5.31:42500..42700
  
  tcpDiscoverySpi:
    localPort: 42500
  
  tcpCommunicationSpi:
    localPort: 42100  
  
  defaultRegion:
    initial: 10435456 
    max: 10435456 
    name: Default_Region

  caches:
    backups: 1
          
  other:
    records: 500
    
