spring:
  application:
    name: ignite-events

logging:
  file: /var/tmp/logs/ignite-events/ignite-events
  level:
    root: INFO
    poc.ignite: debug

ignite:
  other:
    blankNode: false
    clientMode: false
    listener: true
    nNodes: 3
  cache:
    backups: 0
