spring:
  application:
    name: ignite-persistence-data-node

logging:
  file: /var/tmp/logs/ignite-persistence-data-node/ignite-persistence-data-node
  level:
    root: INFO
    poc.ignite: debug

ignite:
  ips:
    - 172.17.5.36:42500..42700
    #- 172.17.5.31:42500..42700
    
  tcpDiscoverySpi:
    localPort: 42500
  
  tcpCommunicationSpi:
    localPort: 42100
  
  dataRegion:
    initial: 268435456 # 256 * 1024 * 1024
    max: 268435456 # 256 * 1024 * 1024
    name: Data_Region
    persistence: true
    active: true
    storagePath: /opt/ngs/setups/apache-ignite-fabric-2.6.0-bin/db
    walPath: ${storagePath}/wal
    walArchivePath: ${walPath}/archive
    
  defaultRegion:
    initial: 268435456 # 256 * 1024 * 1024
    max: 268435456 # 256 * 1024 * 1024
    name: Default_Region
    persistence: false
    active: false    
  
  other:
    nodeName: data-node
