spring:
  application:
    name: ignite-persistence

logging:
  file: /var/tmp/logs/ignite-persistence/ignite-persistence
  level:
    root: INFO
    poc.ignite: debug

ignite:
  ips:
    - 172.17.5.36:42500..42700
    - 172.17.5.31:42500..42700
  
  tcpDiscoverySpi:
    localPort: 42500
  
  dataRegion:
    initial: 512 * 1024 * 1024
    max: 512 * 1024 * 1024
    persistence: true
      
  other:
    clientMode: true
    
