spring:
  application:
    name: ignite-persistence

logging:
  file: /var/tmp/logs/ignite-persistence/ignite-persistence
  level:
    root: INFO
    poc.ignite: debug

ignite:
  ips:
    - 172.17.5.36:42500..42700
    #- 172.17.5.31:42500..42700
  
  tcpDiscoverySpi:
    localPort: 42500
  
  tcpCommunicationSpi:
    localPort: 42100  
  
  dataRegion:
    initial: 10435456 
    max: 10435456 
    name: Data_Region
    active: true
    
  defaultRegion:
    initial: 10435456 
    max: 10435456 
    name: Default_Region

  caches:
    backups: 1
          
  other:
    clientMode: true
    records: 500
    nodes: 2
    start: false
    topVer: 2
    
